### PR TITLE
Prevented crash due to array mutation

### PR DESCRIPTION
**Pull request by JohnCoulton**
I believe this will fix issue #182

### CODE REVIEW

**Comment by ApoorvKhatreja** [comment]
@yannickl Would love to get this merged in!

**Comment by yannickl** [comment]
@ApoorvKhatreja thanks for pinging me. I'm not really active anymore and I can easily miss important information.

**Comment by haulevan** [comment]
Hello @yannickl, could you please help to make a new release version for this MR? Really appreciated it!

**Comment by farrukhaskari1** [comment]
we are still waiting for a release.

**Pull request merged**
